language: php
sudo: false

# Start any dependent services that you might need for your app
#services:
#  - mysql
#  - redis-server
#  - memcached
#  - elasticsearch

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer global require "hirak/prestissimo"

install:
  - composer install --prefer-dist --no-suggest --classmap-authoritative --no-interaction
  - bin/simple-phpunit install

script:
  # this checks that the YAML config files contain no syntax errors
  - ./bin/console lint:yaml config
  # this checks that the Twig template files contain no syntax errors
  #- ./bin/console lint:twig templates
  # this checks that the application doesn't use dependencies with known security vulnerabilities
  - ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock

  # this checks that Doctrine's mapping configurations are valid
  #- ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  - composer lint

  - composer test
