language: php
sudo: false

# Start any dependent services that you might need for your app
#services:
#  - mysql
#  - redis-server
#  - memcached
#  - elasticsearch

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini
  - yes '' | pecl install -f apcu-5.1.8
  - composer self-update
  - composer global require "hirak/prestissimo"

install:
  - composer install --prefer-dist --no-suggest --classmap-authoritative --no-interaction
  - bin/simple-phpunit install

script:
  - composer lint

  # check coding standards
  - composer cs

  # this checks that the application doesn't use dependencies with known security vulnerabilities
  - ./bin/security-checker security:check

  # this checks that Doctrine's mapping configurations are valid
  #- ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

  - composer test
